server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TASK-SERVICE
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
        - id: TODO-SERVICE
          uri: lb://TODO-SERVICE
          predicates:
            - Path=/todo/**
